#!/bin/bash
echo "-----------------------------------"
echo "Tugas 1 SISOP Kelas-A"
echo "-----------------------------------"
echo "Nama : Dendy Arizki Kuswardana"
echo "NPM  : 21083010006"
echo "-----------------------------------"
echo "notes: "
echo "-----------------------------------"
echo "Halo dunia!"
echo "Ini adalah skrip Bash pertamaku di Linux"
