print ('-' * 35)
print ('Tugas 1 SISOP Kelas-A')
print ('_' * 35)
print ('Nama : Dendy Arizki Kuswardana')
print ('NPM : 21083010006')
print ('_' * 35)
print ('notes: ')
print ('-' * 35)
print ('Halo Dunia!')
print ('Ini adalah skrip Bash pertamaku di Linux')
